resources:
- repo: self

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use specific node version'
  inputs:
    version: '8.11.4'

# firebaseDeployToken should be defined in vsts UI
- script: |
    npm install -g npm@6.4.1
    npm update
    bash install.sh
    npm install -g typescript
    npm install -g gulp-cli
    npm install -g firebase-tools
    gulp compile-and-build
    gulp client-unit-test
    firebase deploy --token $token
  env:
    token: $(firebaseDeployToken)

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
